In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent  = [ 'the glass of milk' , 
         'the glass of juice' , 
         'the cup of tea' , 
         'the cup of coffee' , 
         'I am a good boy' ,
         'I am a good developer' , 
         'understand the meaning of words', 
         'your videos are good']

In [4]:
## Define the vocabulary size
voc_size = 10000

In [5]:
## one hot representation
one_hot_repr =[one_hot(words, voc_size) for words in sent]

In [6]:
one_hot_repr

[[9701, 7132, 3000, 6064],
 [9701, 7132, 3000, 1499],
 [9701, 2128, 3000, 4929],
 [9701, 2128, 3000, 7665],
 [1469, 7453, 2938, 7981, 5085],
 [1469, 7453, 2938, 7981, 4788],
 [9191, 9701, 574, 3000, 7640],
 [8210, 9373, 9216, 7981]]

for which index the value for the word will be 1

## word embedding representation

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
  

In [8]:
import numpy as np

In [9]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)

In [10]:
print(embedded_docs)

[[   0    0    0    0 9701 7132 3000 6064]
 [   0    0    0    0 9701 7132 3000 1499]
 [   0    0    0    0 9701 2128 3000 4929]
 [   0    0    0    0 9701 2128 3000 7665]
 [   0    0    0 1469 7453 2938 7981 5085]
 [   0    0    0 1469 7453 2938 7981 4788]
 [   0    0    0 9191 9701  574 3000 7640]
 [   0    0    0    0 8210 9373 9216 7981]]


In [11]:
## feature representation using embedding
dim = 10

In [12]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

c:\Users\himan\OneDrive\Desktop\DATA SCIENCE\ANN_Classification\venv\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 633ms/step


array([[[ 0.04513847, -0.0020222 , -0.02359089, -0.02494032,
          0.00751   , -0.02339441,  0.04175087,  0.01653917,
          0.02789574,  0.04265558],
        [ 0.04513847, -0.0020222 , -0.02359089, -0.02494032,
          0.00751   , -0.02339441,  0.04175087,  0.01653917,
          0.02789574,  0.04265558],
        [ 0.04513847, -0.0020222 , -0.02359089, -0.02494032,
          0.00751   , -0.02339441,  0.04175087,  0.01653917,
          0.02789574,  0.04265558],
        [ 0.04513847, -0.0020222 , -0.02359089, -0.02494032,
          0.00751   , -0.02339441,  0.04175087,  0.01653917,
          0.02789574,  0.04265558],
        [-0.01741087, -0.02393675, -0.02148266, -0.03024031,
          0.00754609,  0.00229007,  0.03341329,  0.00183254,
         -0.044834  , -0.02642235],
        [-0.03160431,  0.04279175, -0.02026719,  0.00062023,
          0.0114089 ,  0.01558338,  0.00943338, -0.02251433,
          0.03911069, -0.03169545],
        [-0.01263075, -0.00126625,  0.01045312, -0.0

In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0, 9701, 7132, 3000, 6064], dtype=int32)

In [22]:
model.predict(np.array([embedded_docs[0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step


array([[[ 0.04513847, -0.0020222 , -0.02359089, -0.02494032,
          0.00751   , -0.02339441,  0.04175087,  0.01653917,
          0.02789574,  0.04265558],
        [ 0.04513847, -0.0020222 , -0.02359089, -0.02494032,
          0.00751   , -0.02339441,  0.04175087,  0.01653917,
          0.02789574,  0.04265558],
        [ 0.04513847, -0.0020222 , -0.02359089, -0.02494032,
          0.00751   , -0.02339441,  0.04175087,  0.01653917,
          0.02789574,  0.04265558],
        [ 0.04513847, -0.0020222 , -0.02359089, -0.02494032,
          0.00751   , -0.02339441,  0.04175087,  0.01653917,
          0.02789574,  0.04265558],
        [-0.01741087, -0.02393675, -0.02148266, -0.03024031,
          0.00754609,  0.00229007,  0.03341329,  0.00183254,
         -0.044834  , -0.02642235],
        [-0.03160431,  0.04279175, -0.02026719,  0.00062023,
          0.0114089 ,  0.01558338,  0.00943338, -0.02251433,
          0.03911069, -0.03169545],
        [-0.01263075, -0.00126625,  0.01045312, -0.0

In [23]:
model.predict(np.array([embedded_docs[0]]))[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step


array([[ 0.04513847, -0.0020222 , -0.02359089, -0.02494032,  0.00751   ,
        -0.02339441,  0.04175087,  0.01653917,  0.02789574,  0.04265558],
       [ 0.04513847, -0.0020222 , -0.02359089, -0.02494032,  0.00751   ,
        -0.02339441,  0.04175087,  0.01653917,  0.02789574,  0.04265558],
       [ 0.04513847, -0.0020222 , -0.02359089, -0.02494032,  0.00751   ,
        -0.02339441,  0.04175087,  0.01653917,  0.02789574,  0.04265558],
       [ 0.04513847, -0.0020222 , -0.02359089, -0.02494032,  0.00751   ,
        -0.02339441,  0.04175087,  0.01653917,  0.02789574,  0.04265558],
       [-0.01741087, -0.02393675, -0.02148266, -0.03024031,  0.00754609,
         0.00229007,  0.03341329,  0.00183254, -0.044834  , -0.02642235],
       [-0.03160431,  0.04279175, -0.02026719,  0.00062023,  0.0114089 ,
         0.01558338,  0.00943338, -0.02251433,  0.03911069, -0.03169545],
       [-0.01263075, -0.00126625,  0.01045312, -0.02460155, -0.02040315,
        -0.00537916,  0.03629735,  0.03361472